= Java RFC5424 Syslog Formatter

== Description

Java RFC5424 formatter library

== Using the Syslog Java Client with Maven

Add the following dependency in your pom.xml:

[source,xml]
----
<dependency>
    <groupId>com.teragrep</groupId>
    <artifactId>rlo_14</artifactId>
    <version>1.0.0</version>
</dependency>
----

== Usage

Sourcing timestamp from long
[source,java]
----
Instant time = Instant.now();
SyslogMessage message = new SyslogMessage()
       .withTimestamp(time.toEpochMilli())
       .withAppName("my_app")
       .withHostname("localhost")
       .withFacility(Facility.USER)
       .withSeverity(Severity.INFORMATIONAL)
       .withMsg("a syslog message");
String actual = message.toRfc5424SyslogMessage();
----

Sourcing timestamp from Instant
[source,java]
----
Instant time = Instant.now();
SyslogMessage message = new SyslogMessage()
       .withTimestamp(time)
       .withAppName("my_app")
       .withHostname("localhost")
       .withFacility(Facility.USER)
       .withSeverity(Severity.INFORMATIONAL)
       .withMsg("a syslog message");
String actual = message.toRfc5424SyslogMessage();
----

Sourcing timestamp from string (parsed and validated)
[source,java]
----
SyslogMessage message = new SyslogMessage()
       .withTimestamp("2023-06-14T16:37:00.000Z")
       .withAppName("my_app")
       .withHostname("localhost")
       .withFacility(Facility.USER)
       .withSeverity(Severity.INFORMATIONAL)
       .withMsg("a syslog message");
String actual = message.toRfc5424SyslogMessage();
----

Sourcing timestamp from string (no validation, useful when you know you have correct format)
[source,java]
----
SyslogMessage message = new SyslogMessage()
       .withTimestamp("2023-06-14T16:37:00.000Z", true)
       .withAppName("my_app")
       .withHostname("localhost")
       .withFacility(Facility.USER)
       .withSeverity(Severity.INFORMATIONAL)
       .withMsg("a syslog message");
String actual = message.toRfc5424SyslogMessage();
----

Adding structured data

[source,java]
----
SyslogMessage message = new SyslogMessage()
        .withTimestamp("2023-06-14T16:37:00.000Z")
        .withAppName("my_app")
        .withHostname("localhost")
        .withFacility(Facility.USER)
        .withSeverity(Severity.INFORMATIONAL)
        .withMsg("a syslog message")
        .withSDElement(
            new SDElement(
                "event_version@48577",
                new SDParam("major", "1"),
                new SDParam("minor", "0"),
                new SDParam("version_source", "source")
            )
        );
String actual = message.toRfc5424SyslogMessage();
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request. 

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

### Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories. 

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories. 
